server:
  address: 0.0.0.0
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: ycl123
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:logback.xml
  level:
    com.ycl.dao.mapper: trace